### ISSUE TITLE
Log actions to STDOUT

### ISSUE THREAD

**Issue by bviktor** [Sinewyk/kf2_autokick#1]
Hey man, thanks a lot for your work, it's MUCH appreaciated. I think I'll try to integrate it fully with kf2-centos because it really is a must-have feature on HoE servers. Loving it!

Anyway, I've written a systemd unit (service) that I use on my CentOS KF2 server to start this process automatically everyime. But there's not much output from the node process, it's like this:

~~~
Jun 25 23:58:42 kf.noobient.com systemd[1]: Stopping KF2 Auto-Kick Server...
Jun 25 23:58:42 kf.noobient.com systemd[1]: Started KF2 Auto-Kick Server.
Jun 25 23:58:42 kf.noobient.com systemd[1]: Starting KF2 Auto-Kick Server...
~~~

It'd be awesome if you could add at least the kick/ban/whatever actions to stdout so it'd become visible in journalctl. Whatcha think?

**Comment by Sinewyk** [comment]
Latest release should add some basic logging.
